force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/EMSO__c.field-meta.xml
<CustomField>
    <fullName>EMSO__c</fullName>
    <label>EMSO</label>
    <precision>13</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular Student</fullName>
            </value>
            <value>
                <fullName>Part-time Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewStudentController.cls
/**
 * Created by Kevin on 28. 02. 24.
 */

public with sharing class NewStudentController {

	@AuraEnabled
	public static Boolean createStudent(String studentJSON) {
		Boolean response = true;

		Student studentPARSED = (Student) System.JSON.deserialize(studentJSON, Student.class);

		Student__c student = new Student__c();
		student.First_Name__c = studentPARSED.firstName;
		student.Last_Name__c = studentPARSED.lastName;
		student.Enrollment_Type__c = studentPARSED.enrollmentType;
		//TODO - EMSO CHECK, EMSO UNIQUEx
		student.EMSO__c = studentPARSED.emso;

		if(String.valueOf(student.EMSO__c).split('').size() == 13) {
			insert student;
		}

		return response;
	}

	//TODO - Wrapper or casting directly in Student__c object?
	public class Student {
		public String firstName;
		public String lastName;
		public String enrollmentType;
		public Long emso;
	}
}